# Generated by Django 4.2.4 on 2023-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230702_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Violet', 'Violet'), ('White', 'White'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Olive', 'Olive'), ('Black', 'Black')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
